---
title: "Introduction to Probability and Statistics"
output:
  html_document:
    css: ../stylesheets/styles.css
---
*MATH 141, Fall 2015*  
*Instructor: [Andrew Bray](https://andrewpbray.github.io/)*  

#### [Syllabus](syllabus.html)

My office hours: M/Tu 2-4, W 2 - 4  
DoJo tutoring: Sun 5-7 PM, Wed 7-9 PM, Thurs 6-8 PM

* * *

### Week Nine

#### Monday, Oct. 26
- Quiz Review
- Inference for Means II
- [Lab 7 Solutions](labs/07-data-wrangling/lab7-key.html)
- [Survey](https://docs.google.com/a/reed.edu/forms/d/1uD1h1zTERdzKuXbRhY5D6kgZvfcaOR1DsFBU_WyBSkc/viewform)
- **Reading for next time**: p. 184-195

#### Tuesday, Oct. 27
- Lab 8

#### Wednesday, Oct 28
- Analysis of Variance (ANOVA)

#### Friday Oct. 30


* * *

### Week Eight

FALL BREAK

* * *

### Week Seven

#### Monday, Oct. 12
- Testing Independence between two categorical variables ([r code](lectures/week-07/07A-Xsq-ind.R))
- [Lab 6 Solutions](labs/06-inf-for-props/inf_for_categorical_data_key.html)
- **Reading for next time**: p. 163-176
- **PS7**: Chapter Three, 37, 39, 42. Chapter Four: 5, 14, 30

#### Tuesday, Oct. 13
- [Lab 7](labs/07-data-wrangling/lab7.html)

#### Wednesday, Oct 14
- Inference for Means ([r code](lectures/week-07/07B-inf-for-means.R))
- **Reading for next time**: p. 176-184

#### Friday Oct. 16
- Inference for Means II
- Quiz

* * *

### Week Six

#### Monday, Oct. 5
- Midterm I Review
- Inference for Categorical Data
- [Lab 5 Solutions](labs/05-normal-dist/normal_distribution_key.html)
- **Reading for next time**: p. [128-133]
- **PS6**: Chapter Three, 1, 11, 12, 15, 20, 24, 28, 30, 35

#### Tuesday, Oct. 6 
- [Lab 6](labs/06-inf-for-props/inf_for_categorical_data.html)

#### Wednesday, Oct 7
- Inference for Categorical Data 2 ([r code](lectures/week-06/06B-CIs-for-props.R))

#### Friday Oct. 9
- The Chi-squared ([r code](lectures/week-06/06C-Xsq.GoF.R))

* * *

### Week Five

#### Monday, Sep. 28
- The Normal Distribution
- [Problem Set 4 Solutions](problem-sets/ps4_key.pdf)
- **Reading for next time**: p. [102-107](http://nb.mit.edu/f/25391)
- **PS5**: Chapter Two, 13, 16, 18, 20, 29, 37, 38, 39, 40

#### Tuesday, Sep. 29
- [Lab 5: The Normal Distribution](labs/05-normal-dist/normal_distribution.html)

#### Wednesday, Sep. 30
- Confidence Intervals

#### Friday Oct. 2
- Midterm I: Ch. 1, 2, and probability appendix
- **Reading for next time**: p. [123-128](http://nb.mit.edu/f/25540)


* * *

### Week Four

#### Monday, Sep. 21
- Review Quiz
- Foundations for Inference
- [Problem Set 3 Solutions](problem-sets/ps3-key.pdf)
- [Lab 3 Solutions](labs/03-probability/lab3-key.html)
- **Reading for next time**: p. [61-81](http://nb.mit.edu/f/25158)
- **PS4**: Chapter Two, numbers 1, 2, 3, 5, 7, 10, [13, 16, 18, 20, 29]

#### Tuesday, Sep. 22
- **No Lab**

#### Wednesday, Sep. 23
- Hypothesis Tests
- Data Analysis in R workshop this afternoon 4-5 pm in ETC 211.

#### Friday Sep. 25
- Hypothesis Tests II: Simulation and the Binomial
- **Reading for next time**: p. [81-102](http://nb.mit.edu/f/25270)



* * *

### Week Three

#### Monday, Sep. 14
- Review Quiz
- Probability I
- [Problem Set 3](problem-sets/ps3.pdf)

#### Tuesday, Sep. 15
- [Lab 3: Probability](labs/03-probability/probability.html)

#### Wednesday, Sep. 16
- Probability II: conditional probability

#### Friday Sep. 18
- Probability III: random variables
- Quiz 2

* * *

### Week Two

#### [Monday, Sep. 7] No Class

#### Tuesday, Sep. 8
- [Lab 1 : Intro to Data](labs/02-intro_to_data/intro_to_data.html)
   - [Solutions](labs/02-intro_to_data/lab1-key.html)

#### Wednesday, Sep. 9
- Describing Data
- **PS2**: Chapter one, numbers 24, 26, 33, 36, 37, 40, 42, 47, 50. These will be
collected Monday in class.


#### Friday Sep. 11
- Ch. 1 Quiz

* * *

### Week One

#### Monday, Aug. 31
- Data taxonomy
- **HW**: 
    - Sign up for an office visit at [nb.mit.edu](http://nb.mit.edu/f/24222).
    - Confirm that you can log in to [https://rstudio.reed.edu/](https://rstudio.reed.edu/).
    If you're not able to log in, please email me.

#### Tuesday, Sep. 1
- Lab 0 : Intro to R and RStudio
    - [Lab](labs/01-intro_to_r/intro_to_r.html) ([Rmd](labs/intro_to_r/intro_to_r.Rmd))

#### Wednesday, Sep. 2
- Review reading group and lab submission procedures.
- Descriptive vs inferential statistics
- Principles of data collection

#### Friday, Sep. 4
- Experimental design
- **PS1**: Please work through problems 1, 4, 6, 8, 10, 11, 15, 16, 17, 19, 22 in the
exercises at the end of chapter one (the first one is labeled 1.1 on page 43). These
will be collected at the beginning of class next Wednesday.

