---
title: "Notes for Next Time"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Textbook

- **Definition of p-value** (ch. 2): What's this business about "favorable to 
the null hypothesis?" For decisions, can we move to "data is consistent/inconsistent
with the model"?

- **Consider removing 2.3.6**: Isn't it simpler to say, "always use two-sided
tests?" If we spend time on how not to lie with statistics, I'd opt for a discussion
of multiple comparisons.

- **Null vs Sampling Distribution**: Seems like we could be clearer about the (small)
difference between these two distributions.


# General

- Spend more time on data visualization before continuing on to probability/inference.
Consider moving around sampling/design a bit.

- Don't forget to use the Salish Sea Feet example for hypothesis testing.

- Gather examples from previous senior theses
    - ANOVA - Michael Pitts brainwave data

- Add questions to problem sets from outside of the book (e.g. stat literacy read
this news/journal article and comment).

- Be more explicit about RV notation (Bernoulli, Binomial, Poisson) with E and V
for each.

- Be more explicit and spend more time addressing power.

- Collapse approaches to inference to "computational" and "theoretical".

- Have homeworks and labs due on different days.

- Video link for Data Viz: https://www.youtube.com/watch?v=14VYnFhBKcY

- For second midterm, have it be take home but advertise that beforehand.

- For taxonomy of data, use some other letters besides X, Y, W.