---
title: "Groups"
author: "Andrew Bray"
date: "Friday, October 17, 2014"
output: html_document
---

## Section I
1. Emma, Sam, Annakate: volleyball
2. Elizabeth, Allie, Sibonelo: work force, agriculture, climate
3. Cleo, Yujia, Grace: voting, child psych, public health
4. Shelbie, Shanda, Sylvia: ecology (ideally honeybees), medicine, education, BEES/Ecology, Public Health, Childhood Psychology.
5. Jacqui, Whitney, Melissa: music
6. Rose, JungWon, Dana: sports
7. Amanda, Michelle, Buyan
8. Celine, Sara, Akchheta
9. Caiyun, Prarthana, Milani
10. Alison, Emily, Melissa D

Michelle: child psych, sports, voting
Amanda: education, election predictions, psychology of learning
Buyan: public health, childhood psychology, education

Celine: biology (genetics), public health, education
Sara: public health, psych, voting behavior
Akchheta: public health, economics, and psychology.

Caiyun: econ, psych, environmental
Prarthana: Economics, Finance, Public Health
Milani

Alison: ecology, chemistry, geology
Emily: Geology, Ecology, Public Health
Melissa



## Section II
1. Bharati, Meher, Maame: econ, voting behavior, sports
2. Arda, David, Thalia
3. Dani, Kate, Thao
4. Nikita, Amna, Anne F
5. Claire, Mahima, Van
6. Dani, Kate, Thao
7. Fei, Tu, Steph
8. Kelu, Siyao
9. Anne W., Liz

Thalia

David: Tennis, soccer, rugby; econ; bio
Arda: football, sports, health/epi
Anne W: public health, ecology, sports.


Nikita: voting/politics, relationship between education and wealth, environmental
Amna: voting, public health, child psych
Siyao


Claire: engineering, equine, non-profits (neuropathy)
Mahima: demograpy, technology
Van

Dani: Ebola, Ecology, Epidemiology in general
Kate: epidemiology, general public health, disease/general ecology
Thao: genetics, molecular biology, psychology

Fei: Public health, Childhood psychology, Voting behavior
Tu: public health, childhood psychology, voting behavior
Steph: public health, voting behavior, and ecology

Kelu
Siyao
Anne F
Liz: public health, alpacas, ecology


