---
title: "Data Wrangling"
output:
  html_document:
    theme: cerulean
    highlight: pygments
    css: ../lab2.css
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
library(dplyr)
library(ggplot2)
library(oilabs)
```

<div id="boxedtext">
A note on workspaces: Before we get started with the lab, let’s take a moment to
review our R Markdown workflow and remind ourselves about workspaces in R. The 
workspaces of the console and the workspaces of your R Markdown document are not
the same. Therefore, if you define a variable only in the Console and then try 
to use that variable in your R Markdown document, you’ll get an error. This might
seem frustrating at first, but it is actually a feature that helps you in the 
long run. In order to ensure that your report is fully reproducible, everything
that is used in the report must be defined in the report, and not somewhere else.

It is your responsibility, and an important learning goal of this course, that 
you master the skills for creating fully reproducible data analysis reports. 
Below are some tips for achieving this goal:

- Always work in your R Markdown document, and not in the Console.
- Knit early, and often, always checking that the resulting document contains everything you expected it to contain.
    
</div> 

* * *

<div id="template">
**Your reproducible lab report:** Before you get started, download the R Markdown 
template for this lab. Remember all of your code and answers go in this document.
</div>


## Hot Hands

Basketball players who make several baskets in succession are described as 
ha


* * *

<div class="oyo">

## On your own

### Comparing Kobe Bryant to the Independent Shooter

-   Using `calc_streak()`, compute the streak lengths of `sim_basket`, and
    save the results in a data frame called `sim_streak`. Note that since the 
    `sim_streak` object is just a vector and not a variable in a data frame, we 
    don’t need to first select it from a data frame like we did earlier when we 
    calculated the streak lengths for Kobe’s shots.

-   Describe the distribution of streak lengths. What is the typical streak 
    length for this simulated independent shooter with a 45% shooting percentage?
    How long is the player's longest streak of baskets in 133 shots? Make sure
    to include a plot in your answer.

-   If you were to run the simulation of the independent shooter a second time, 
    how would you expect its streak distribution to compare to the distribution 
    from the question above? Exactly the same? Somewhat similar? Totally 
    different? Explain your reasoning.

-   How does Kobe Bryant's distribution of streak lengths compare to the 
    distribution of streak lengths for the simulated shooter? Using this 
    comparison, do you have evidence that the hot hand model fits Kobe's 
    shooting patterns? Explain.

-   What concepts from the textbook are covered in this lab? What concepts, if 
    any, are not covered in the textbook? Have you seen these concepts elsewhere,
    e.g. class, videos, textbook, previous labs, or homework problems? Be
    specific in your answer.

</div>
