---
title: "Shared Projects"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Collaborative Data Analysis {.build}

- To access the servers from off-campus, you will need to contact CUS to
get set-up with VPN access.

To access your shared project:

1. Navigate to `http://andrewpbray.github.io/intro/project/group-rosters.html`
2. Click on the the link for your group
3. Use your same login to access the new shared project server


## Shared Projects {.build}

- Only your group members and I have access to these files.
- Anyone can add/delete/modify files and work simultaneously.
- This server is **completely separate** from the main RStudio server.

`rstudio-dev.reed.edu` versus `rstudio.reed.edu`


## Group Project Organization {.build}

The following directions only apply if a group mate hasn't already done them
in a previous lab.

1. Click "New Folder" in the Files tab and add a folder called `proposal`.
2. Create three other new folders in the main directory: `data`, `report`, and
`more`.
3. Create a new R Markdown file and save it as `revised-proposal.Rmd` in the
`proposal` folder.
4. Create another new R Markdown file and save it as `report-draft.Rmd` in
the `report` folder.

This software is brand new, so please email me if you notice any bugs or have
any suggestions.


## On to the lab

You can now sign out of `rstudio-dev.reed.edu` and into `rstudio.reed.edu` to
work on the lab as usual.
